# Generated by Django 5.2.8 on 2026-01-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
