# Generated by Django 5.2.8 on 2026-01-17 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_record_email_alter_record_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Customer',
        ),
    ]
